## YAML Template.
---
groups :
    - name : Group1
      members :
        - alice
        - bob
        - charlie
    - name: Group2
      members :
        - daphnie
        - charlie
        - ccc
configuration : 
    - name : alice
      ip : 128.237.175.181
      port : 12344
    - name : bob
      ip : 128.237.175.181
      port : 14255
    - name : charlie
      ip : 128.237.175.181
      port : 12998
    - name: daphnie
      ip : 128.237.175.181
      port : 1985
    - name : ccc
      ip : 128.237.175.181
      port : 12362
    - name : logger
      ip : 128.237.175.181
      port : 1987
    
sendRules : 
    - action : drop
      src : alice
      dest : bob
    
receiveRules :
    - action : drop
      kind : impossiblekind
